apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-cicd
  namespace: cicd
spec:
  storageClassName: microk8s-hostpath
  accessModes: 
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi