apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-pipeline
  namespace: cicd
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: clusterrole-pipeline
rules:
- apiGroups: 
  - ""
  - triggers.tekton.dev
  - tekton.dev
  resources: 
  - '*'
  verbs: 
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: clusterrole-binding-pipeline
roleRef:
  kind: ClusterRole
  name: clusterrole-pipeline
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: sa-pipeline
  namespace: cicd
---