apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: eventlistener
  annotations:
    tekton.dev/payload-validation: "true"
  namespace: cicd
spec:
  serviceAccountName: sa-pipeline
  resources:
    kubernetesResource:
      serviceType: NodePort
  triggers:
  - name: github-pr-group
    interceptors:
    - name: "validate GitHub payload and filter on eventType"
      ref:
        name: "github"
      params:
      - name: "secretRef"
        value:
          secretName: github-secret
          secretKey: secretToken
      - name: "eventTypes"
        value: ["push"]
    bindings:
      - ref: pipeline-binding
    template:
      ref: pipeline-template
