
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: pipeline-template
  namespace: cicd
spec:
  params:
  - name: gitrevision
    description: The git revision
    default: master
  - name: gitrepositoryurl
    description: The git repository url
  - name: contenttype
    description: The Content-Type of the event
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      generateName: pipeline-run-sample-app-
      namespace: cicd
    spec:
      pipelineRef:
        name: pipeline-sample-app
      podTemplate:
        securityContext:
          fsGroup: 65532
      serviceAccountName: sa-pipeline
      workspaces:
      - name: shared-data
        persistentVolumeClaim:
          claimName: pvc-cicd
      - name: git-credentials
        secret:
          secretName: git-credentials
      params:
      - name: repo-url
        value: git@github.com:ngocHung2000/argocd-deployment-strategies.git