apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pipeline-sample-app
  namespace: cicd
spec:
  description: | 
    This pipeline clones a git repo, then echoes the README file to the stout.
  params:
  - name: gitrepositoryurl
    type: string
  - name: gitrevision
    type: string
  - name: contenttype
    type: string
  workspaces:
  - name: shared-data
  - name: git-credentials
  tasks:
  - name: task-clone-source
    taskRef:
      name: task-clone-source
    workspaces:
    - name: output
      workspace: shared-data
    - name: ssh-directory
      workspace: git-credentials
    params:
    - name: url
      value: $(params.gitrepositoryurl)
  - name: task-view-payload
    taskRef:
      name: task-view-payload
    workspaces:
      - name: source
        workspace: shared-data
    runAfter:
      - task-clone-source
    params:
      - name: gitrevision
        value: $(params.gitrevision)
      - name: gitrepositoryurl
        value: "$(params.gitrepositoryurl)"
      - name: contenttype
        value: "$(params.contenttype)"